module.exports = [
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
  { name: "clean.eth", price: 23.81 },
];
